#!/bin/dash

add_new_folder() {
	cd ~/Music
	dir="`find * -follow -type d | dmenu -i -p Add:`"

	if ! [ -z "$dir" ] ; then
		mpc add "$dir"
		mpc play
	fi
}

search_a_song() {
	song_name=`mpc playlist | dmenu -i -p Search:`
	if ! [ -z "$song_name" ]; then
#ex :Adam Lambert - Never Close Our Eyes
		result=`echo "$song_name" | sed 's/.*\ -\ //g'`
		echo $result
		mpc searchplay "$result"
	fi
}

do_ggsearch() {
	q_key=`cat ~/.gshist | dmenu -i -p Google:`
	
	if grep -q "$q_key" "$HOME/.gshist" ; then
		echo "ok"
	else
		echo $q_key >> ~/.gshist
	fi

	if ! [ -z "$q_key" ]; then
		firefox --new-tab http://www.google.com.vn/search?q="$q_key"
	fi
}

do_dictionary_lookup() {
	q_key=`cat ~/.dicthist | dmenu -i -p Keyword:`
	
	if grep -q "$q_key" "$HOME/.dicthist"; then
		echo "ok"
	else
		echo $q_key >> ~/.dicthist
	fi

	notify-send -u low "`sdcv -n "$q_key" | tail -n +4 | head -30`"
}

control="1: add new folder\n2: search for a song\n3: clear mpd playlist\n4: do a google search\n5: dictionary lookup"
choose=`printf "$control" | dmenu -i -p Task:`
case $choose in
"1:"*)
	sleep 0.1
	add_new_folder
	;;
"2:"*)
	sleep 0.1
	search_a_song
	;;
"3:"*)
	mpc clear
	;;
"4:"*)
	sleep 0.1
	do_ggsearch
	;;
"5:"*)
	sleep 0.1
	do_dictionary_lookup;;
esac
