#!/bin/dash

add_new_folder() {
	cd ~/Music
	dir="`find * -follow -type d | dmenu -i -p Add:`"

	if ! [ -z "$dir" ] ; then
		mpc add "$dir"
		mpc play
	fi
}

search_a_song() {
	song_name=`mpc playlist | dmenu -i -p Search:`
	if ! [ -z "$song_name" ]; then
#ex :Adam Lambert - Never Close Our Eyes
		result=`echo "$song_name" | sed 's/.*\ -\ //g'`
		echo $result
		mpc searchplay "$result"
	fi
}

open_url() {
	q_key=`cat ~/.urlhist | dmenu -i -p Url:`

	if grep -q "$q_key" "$HOME/.urlhist"; then
		echo "ok"
	else
		echo $q_key >> ~/.urlhist
	fi

	firefox --new-tab "$q_key"
}

do_ggsearch() {
	q_key=`cat ~/.gshist | dmenu -i -p Google:`
	
	if grep -q "$q_key" "$HOME/.gshist" ; then
		echo "ok"
	else
		echo $q_key >> ~/.gshist
	fi

	if ! [ -z "$q_key" ]; then
		firefox --new-tab http://www.google.com.vn/search?q="$q_key"
	fi
}

do_dictionary_lookup() {
	q_key=`cat ~/.dicthist | dmenu -i -p Keyword:`
	
	if grep -q "$q_key" "$HOME/.dicthist"; then
		echo "ok"
	else
		echo $q_key >> ~/.dicthist
	fi

	notify-send -u low "`sdcv -n "$q_key" | tail -n +4 | head -30`"
}

control="m1: add folder\nm2: search\nm3: clear playlist\nw1: google search\nw2: goto url\ns1: dictionary lookup"
choose=`printf "$control" | dmenu -i -p Task:`
case $choose in
"m1:"*)
	sleep 0.1
	add_new_folder
	;;
"m2:"*)
	sleep 0.1
	search_a_song
	;;
"m3:"*)
	mpc clear
	;;
"w1:"*)
	sleep 0.1
	do_ggsearch
	;;
"w2:"*)
	sleep 0.1
	open_url
	;;
"s1:"*)
	sleep 0.1
	do_dictionary_lookup;;
esac
